""" Generated by Agent """

from pkg.calculator import Calculator

calculator = Calculator()

test_cases = [
    ("3 + 5", 8),
    ("10 - 4", 6),
    ("3 * 4", 12),
    ("10 / 2", 5),
    ("3 * 4 + 5", 17),
    ("2 * 3 - 8 / 2 + 5", 7),
    ("", None),
]

for expression, expected_result in test_cases:
    try:
        result = calculator.evaluate(expression)
        print(f"Expression: {expression}, Result: {result}, Expected: {expected_result}, Pass: {result == expected_result}")
    except Exception as e:
        print(f"Expression: {expression}, Error: {e}")